---
- name: Install Apache HTTPD via yum
  yum: name={{ item }} state=present
  with_items: "{{ apache_packages }}"

- name: Put our httpd.conf file in place
  copy: src=httpd.conf dest={{ httpd_conf_path }}/httpd.conf owner=root group=root mode=0644 backup=yes

- name: Put our ssl.conf file in place
  copy: src=ssl.conf dest={{ ssl_conf_path }}/ssl.conf owner=root group=root mode=0644 backup=yes

- name: Ensure virtual host path exists within the httpd path
  file: path=/etc/httpd/vhosts state=directory

- name: Enable HTTPD service
  service: name=httpd state=started enabled=yes

- name: Create HTTP (80) filter rule in IPTables config
  lineinfile: dest=/etc/sysconfig/iptables state=present insertafter="^:OUTPUT " line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
  notify:
    - restart iptables

  - name: Create HTTPS (443) filter rule in IPTables config
  lineinfile: dest=/etc/sysconfig/iptables state=present insertafter="--dport 80" line="-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT"
  when: use_https == 1
  notify:
    - restart iptables
