---
- name: Install Apache HTTPD via yum
  yum: name={{ item }} state=present
  with_items: "{{ apache_packages }}"

- name: Put our httpd.conf file in place
  copy:
    src: "httpd.conf"
    dest: "{{ httpd_conf_path }}/httpd.conf"
    owner: "root"
    group: "root"
    mode: 0644
    backup: "yes"

- name: Put our ssl.conf file in place
  template:
    src: "ssl_conf.j2"
    dest: "{{ ssl_conf_path }}/ssl.conf"
    owner: "root"
    group: "root"
    mode: 0644
    backup: "yes"

- name: Ensure virtual host path exists within the httpd path
  file: path=/etc/httpd/vhosts.d state=directory

- name: Enable HTTPD service
  service: name=httpd state=started enabled=yes
